#!/usr/bin/env bash

CONFIG=~/.stitchrc

make_email() {
  base=`grep -F 'base_email:' $CONFIG  | cut -d':' -f 2-`
  user=`echo $base | cut -d'@' -f 1`
  domain=`echo $base | cut -d'@' -f 2-`
  
  printf '%s+%s+%s@%s' $user $1 $2 $domain
}

get_name() {
  content=$(curl -L bitbucket.org/$1 2>/dev/null)
  
  echo $content |\
    sed ':a;N;$!ba;s/\n/ /g' |\
    grep -Po '<h1>.*?<' |\
    head -n1 |\
    sed -n 's/<h1>[ ]*\(.*\)[ ]*</\1/p'
}

make_name() {
  one=$(get_name "$1")
  two=$(get_name "$2")
  
  printf '%s and %s' "$one" "$two"
}

export GIT_AUTHOR_EMAIL=$(make_email $1 $2)
export GIT_AUTHOR_NAME=$(make_name $1 $2)

echo $GIT_AUTHOR_EMAIL
echo $GIT_AUTHOR_NAME